module Edmunds
  module Vehicle
    module Specification
      module Equipment
        # Static Equipment API data
        AVAILABILITY =    %w[ Standard Optional ]

        EQUIPMENT_TYPE =  %w[ AUDIO_SYSTEM COLOR ENGINE MANUFACTURER MIRRORS
                              OPTION OTHER TELEMATICS TIRES ]

        EQUIPMENT_NAMES = %w[ 1ST_ROW_SEATS 2ND_ROW_SEATS 3RD_ROW_SEATS 4TH_ROW_SEATS 5TH_ROW_SEATS
                              AIR_CONDITIONING AIRBAGS AUDIO_SYSTEM BRAKE_SYSTEM CARGO_DIMENSIONS
                              COLLISION_SAFETY_SYSTEM COLOR CONVERTIBLE_ROOF DIFFERENTIAL DOORS
                              DRIVE_TYPE DRIVER_SEAT ENGINE EXTERIOR_DIMENSIONS EXTERIOR_LIGHTS
                              FRONT_PASSENGER_SEAT INSTRUMENTATION INTERIOR_DIMENSIONS MANUFACTURER
                              MIRRORS MOBILE_CONNECTIVITY NAVIGATION_SYSTEM PARKING_AID POWER_OUTLETS
                              SEATBELTS SEATING_CONFIGURATION SECURITY SPARE_TIRE/WHEEL
                              SPECIFICATIONS STEERING STEERING_WHEEL STORAGE SUNROOF SUSPENSION
                              TECHNOLOGY_FEATURE TELEMATICS TIRES TRAILER_TOWING_EQUIPMENT
                              TRANSMISSION TRUCK_BED TRUNK VIDEO_SYSTEM WARRANTY WHEELS WINDOWS ]

      end
    end
  end
end
